name: Draw ZMK keymaps

on:
  workflow_dispatch:

  push:
    paths:
      - "config/*.keymap"
      - "config/info.json"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main

    permissions:
      contents: write

    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"

      draw_args: "keymap:'--qmk-info-json config/info.json'"

      commit_message: "Update keymap diagram"
      fail_on_error: true
